#!/usr/bin/env python3
"""Regenerate docs/practice/quiz.md from questions.json.

    uv run python/quiz/export_markdown.py

Keeping the browsable version generated means the JSON stays the single source
of truth -- edit questions there, never in the Markdown.
"""

import json
import os
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
BANK = os.path.join(HERE, "questions.json")
OUT = os.path.abspath(os.path.join(HERE, "..", "..", "docs", "practice", "quiz.md"))

def wrap(text, indent=""):
    """Wrap a paragraph at 80 columns, the width the rest of docs/ is written to.

    Long words -- URLs, `code spans` -- are left intact rather than broken.
    """
    return textwrap.fill(text, width=80, initial_indent=indent,
                         subsequent_indent=indent, break_long_words=False,
                         break_on_hyphens=False)


TOPIC_TITLES = {
    "pinhole": "The pinhole model",
    "K": "The K matrix",
    "D": "The D vector",
    "resize": "Resize, crop and ROI",
    "undistort": "Undistortion",
    "calibration": "Calibration in practice",
}
TOPIC_DOCS = {
    "pinhole": "01_pinhole_and_projection.md",
    "K": "02_the_K_matrix.md",
    "D": "03_the_D_vector.md",
    "resize": "04_resize_crop_and_roi.md",
    "undistort": "05_undistortion.md",
    "calibration": "06_calibration_in_practice.md",
}


def main() -> None:
    with open(BANK, encoding="utf-8") as fh:
        data = json.load(fh)
    qs = data["questions"]

    out = ["# Quiz", "",
           f"{len(qs)} questions covering the whole repository. Answers are "
           "folded away, so you can",
           "read this page straight through and still test yourself.", "",
           "Prefer it interactive? The same bank runs in the terminal, with "
           "numeric answers",
           "graded to a tolerance:", "",
           "```bash",
           "uv run python/quiz/run_quiz.py                 # 10 random questions",
           "uv run python/quiz/run_quiz.py -n 28           # the whole bank",
           "uv run python/quiz/run_quiz.py --topic D       # one topic",
           "uv run python/quiz/run_quiz.py --study         # answers, no quiz",
           "```", "",
           "<!-- generated by python/quiz/export_markdown.py -- do not edit by "
           "hand -->", ""]

    seen = []
    for q in qs:
        if q["topic"] not in seen:
            seen.append(q["topic"])

    for topic in seen:
        title = TOPIC_TITLES.get(topic, topic)
        doc = TOPIC_DOCS.get(topic)
        out.append(f"## {title}")
        if doc:
            out.append("")
            out.append(f"Theory: [{doc}](../course/{doc})")
        out.append("")
        for q in [x for x in qs if x["topic"] == topic]:
            out.append(wrap(f"**{q['id']}.** {q['q']}"))
            out.append("")
            if q["type"] == "mc":
                for i, opt in enumerate(q["options"]):
                    out.append(wrap(f"- `{chr(ord('a') + i)}`  {opt}",
                                    indent="").replace("\n", "\n  "))
                answer = f"**{chr(ord('a') + q['answer'])})** " \
                         f"{q['options'][q['answer']]}"
            else:
                out.append("- *(numeric answer)*")
                answer = f"**Answer:** {q['answer']}"
            out.append("")
            out.append("<details><summary>answer</summary>")
            out.append("")
            out.append(wrap(answer))
            out.append("")
            out.append(wrap(q["explain"]))
            out.append("")
            out.append("</details>")
            out.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out).rstrip() + "\n")
    print(f"wrote {OUT}  ({len(qs)} questions, {len(seen)} topics)")


if __name__ == "__main__":
    main()
